### PR TITLE
Bin2hcdev

### PR DESCRIPTION
**Pull request by christopherreay**
hccore and some updates/fixes to hccdev

### CODE REVIEW

**Comment by zippy** [comment]
I just updated https://docs.google.com/document/d/1IaW4G8IiKDBF6XdvhzmyjBzknaUam4Q_TGsawVv2PQo/edit#
To document how I think all the options should work for hcdev init, but I'm open to other possibilities too.

**Comment by christopherreay** [comment]
init interactive never worked. It should work now. Im getting fed up of whatever nonsense Ive managed to pull with my commit history.

**Comment by zippy** [comment]
Well, I know it worked at one point, because I actually did try it despite the misspelling that go in there somehow...  But that's what I get for not having tests on this stuff, so it's also time to prioritize #246 which I just did.

**Comment by christopherreay** [comment]
yeah i dunno. Ive blown away my own work. just too aggravated going round and round with stuff I already fixed. Ill dig the commits after a glass of water. Sorry eric

**Comment by christopherreay** [comment]
I dunno. I cant find any of my commits to hcdev, or to the .interactive parts of the scripts (string rejigging and stuff,that I readin the diffs just before I committed them earlier. So.. . Im still looking)

**Comment by zippy** [comment]
I kept the old bin2hcdev branch, I'll push it..

**Comment by christopherreay** [comment]
Right, so I just deleted the interactive command, since its complete irrelevant now anyway. There is a bunch of mess in there, but probably that doesnt matter, we can just not document it, and probabaly no one will find it anyway. Ill sort that out when I have some time spare. Umm. Oh yeah, and there is this issue with not being able to rebase onto master because of the holochain.apps.init.interactive file. Hang on

**Comment by christopherreay** [comment]
I have no idea why this wont rebase onto master. Any idea?

**Comment by christopherreay** [comment]
so we decided to just merge the pull request, even though no one could be bothered to work out why it was wrong, since the commits should have been orthoganal to any other development

**Pull request merged**
