### PR TITLE
279 bin2hcdev 307 shifts in hcdev 309 go scenario

### PR DESCRIPTION
**Pull request by christopherreay**
Hi

Could you please resolve all merge conflicts and  Ill continue development on this branch when it has been merged to master and I can continue with my own patches. 

Un fourtuntable I  am not able to resolve the 15 or so merge conflicts introduced by your code that you merged into my working branch.

Saludos

DayZee

### CODE REVIEW

**Comment by zippy** [comment]
Will do.

**Comment by zippy** [comment]
Done.

**Comment by christopherreay** [comment]
thank you

**Comment by zippy** [comment]
@christopherreay  it looks like you merged this branch into master? Why is that?  That doesn't seem right to me because the work here's not done and has lots of cleanup before it should be merged into master.

**Pull request merged**
