### PR TITLE
Split dockerfiles into one for each of two different use-cases

### PR DESCRIPTION
**Pull request by timotree3**
In this branch I have done the following:

* Reorganized the `docker` directory structure a bit.
* Made changes to the existing `Dockerfile` to make it more lightweight.
* Create a new `Dockerfile` running the Debian/Jessie version of golang's docker which uses some usability tricks of the existing `Dockerfile`
* Cleaned up some files that are no longer useful.
* Tweaked the `.dockerignore` so that changing something about `Dockerfile` doesn't force the whole thing to recache.
* Redone the UID mimicking system a bit.

### CODE REVIEW

**Comment by timotree3** [comment]
Any feedback or concerns?

**Comment by zippy** [comment]
Timo, this looks great as far as I can tell.  The one things that's missing would be a short readme orienting folks to the different ways to use the two docker images.  I know this stuff is in flux, but from what I can tell, the build/run scripts will use the hc-devtools version (which seems appropriate), but it would be nice for there to be a short readme that says this, and also how to run the lightweight version if desired, either by editing the script, or by adding an environment variable you can set, or an argument to the run/build sripts themselves.

**Comment by christopherreay** [comment]
As far as I can see what is missing here is a formal document showing what the expected use cases are, and how the tools available enable each use case.

**Comment by zippy** [comment]
I'm ok with it being informal in the readme, i.e. a brief description of why one would choose one over the other.

**Comment by christopherreay** [comment]
> Reorganized the docker directory structure a bit.
ok
> Made changes to the existing Dockerfile to make it more lightweight.
I think most of this looks great. I dont know of any use case which doesnt require that the docker container is running as the same user as the host user, or otherwise can add files into the developer/user's filesystem in a coherent fashion
> Create a new Dockerfile running the Debian/Jessie version of golang's docker which uses some usability tricks of the existing Dockerfile
I do not have a clear picture as to what this is for. Please point me to some documentation about it, or otherwise explaination
> Cleaned up some files that are no longer useful.
which commits does this refer to?
>Tweaked the .dockerignore so that changing something about Dockerfile doesn't force the whole thing to recache.
In my opinon this is an accidental conflation of the needs of the Dockerfile developer, and the needs of the actual repository. At this stage, I think that .dockerignore is still a tool which is a bit overpowered given the openness of possible future changes. 
> Redone the UID mimicking system a bit.
Sounds good. I cant find that in the commits. Could you point me to which commit this refers to? Im considering using the holochain/bin scripts to dynamically write the contents of dockerfiles, which actually is a much better solution to this than the ENTRYPOINT solution offered by docker

*General Notes:*
I dont understand still the usecase for a "holochain" user inside containers.

**Comment by christopherreay** [comment]
@zippy What I mean is, I dont think there is explaination of what the usecases are

**Comment by christopherreay** [comment]
Here's a start at a complete list of all the use cases.
https://github.com/metacurrency/holochain/wiki/Dockerfile-Design-by-Use-Case

as far as I can see, all development of Dockerfiles should be in reference to this or to some other document with the same basic purpose. And design decisions would do well to be justified in such a document

**Comment by christopherreay** [comment]
@GerryG 

Hi, I know you have some content about long running development containers. Is there writing about it? And links?

**Comment by zippy** [comment]
I agree that 2 & 3 are exactly the same, it doesn't make sense to separate them, we want to encourage all app developers to do multi-node testing.

**Comment by timotree3** [comment]
@christopherreay 

3. Debian/Jessie because it is the most complete system available as a golang variant.
4. https://github.com/metacurrency/holochain/pull/205/commits/68acdc0a99e9280c96b1576d7d55c72c4c1bb77a
5. One cannot run docker from inside docker which is why I can justify putting these things in the `.dockerignore`

**Comment by timotree3** [comment]
The documentation of how to use the docker for development is the same as already in the README.

For those building containers which are used for multi-node testing, they should use `FROM metacurrency/holochain:alpine`.

@zippy I'll put this information in a `docker/README.md` file.

**Comment by christopherreay** [comment]
*  > I agree that 2 & 3 are exactly the same, it doesn't make sense to separate them, we want to encourage all app developers to do multi-node testing.
  * The level of fiddle of english necessary to pick this apart is quite a lot. However, what Im saying is that the dockerfile that multinode testing uses for containers, and the dockerfile that one might create for a user, e.g. to fiddle with an app, could be different. Might be different. Maybe. But, at the moment, I cant think of any differences, though we used to think there were, but now Im not so sure.

> The documentation of how to use the docker for development is the same as already in the README.
  * There isnt **any** accurate, useful documentation, and as far as I know, no design document, short of the things that I am working on, which are somewhat incomplete, though the designs are clear in my  mind, and the scripts (and dockerfiles) to support them are pretty close.
  * `docker for development` is quite vague, which is why Ive created a document showing the use cases. It seems resonable to make justifications based on the use cases as presented, and to extend those use cases as required.

> For those building containers which are used for multi-node testing, they should use FROM metacurrency/holochain:alpine.
  * this just isnt true. 
      1. multi-node tests use the current uid for storing logs
      2. the namespace "holochain:alpine" is not specific to our domain, and, therefore, in my opinion, not a good choice.

In so far as the improvment in filesize and build time, I think this pull request does a good job. As for the changes in functionality and categorisation of the "two usecases", I dont think there justification for them, neither do I think that they are coherent with the current functionality, nor any design I have seen. Certainly they are not coeherent with the designs I am working in, which I have done my very best to document: 
  * https://github.com/metacurrency/holochain/wiki/Holochain-Development-Introduction
    * approximately the first half of this document is current, though the scripts do not support it. #204 goes most of the way to making this documentation actually accurate lol.
  * https://github.com/metacurrency/holochain/wiki/dayzeerationale
    * this document is also inaccurate and incomplete, though the last part is accurate as to the design rationale.
  *  https://github.com/metacurrency/holochain/wiki/Dockerfile-Design-by-Use-Case
    * it would be nice to flesh this out.

**notes**
In general, it would be nice to flesh out the overall picture of the whole system, each of the user use-cases, and complete the dockerfile designs with respect to that complete picture.

**Comment by christopherreay** [comment]
>Debian/Jessie because it is the most complete system available as a golang variant.
68acdc0

    * yes, but why do we want any such image? What is the reason for needing one? Also, its perfectly simple to add go to an ubuntu or whatever, and I dont see any justification for using "govariants"


> One cannot run docker from inside docker which is why I can justify putting these things in the .dockerignore
  * one can run docker from inside docker, and there is a good usecase for a developer tool which would do so. That is not a priority for me at this time.
  * Being able to see or read the dockerfiles from inside the container might be useful for something, it might not.
    * the two things that happen inside containers are running hc/bs/etc, or running tests (bash scripts). Whilst its clear that hc/bs/etc dont ever need to see the dockerfiles, to actually run *tests on the dockerfiles* it might be useful to be able to see them from inside the container.

**Comment by christopherreay** [comment]
As I have pointed out, it would be good to enter into this process at the start, and actually design the requirements of the dockerfiles against the requirements of a systems architecture and user experience, rather than trying to squeeze all that into a response to a pull request.

TODO:
* create a clear usecase document and systems architecture for user experience
* create designs for dockerfiles against the above requirements
* have mostly complete documentation for both of these things, round abouts, and am very up for discussing the details

QUESTIONS:
* what is the "holochain" user for?
* why has the "uid" functionatliy been removed for the dockerfile targetted at multi-node testing. Its possible it might work, but there is no documentation as to a design in which this would fit.
* What is the reason for having a "debain/jessie", or otherwise "more fully fledged" *nix base for an image?

**Comment by timotree3** [comment]
I will update the pull request with a bit more documentation today.

**Comment by timotree3** [comment]
@zippy Does the new file `docker/README.md` meet the needs of documentation you were talking about?

**Comment by christopherreay** [comment]
The documentation looks good to me.

Only thing I would comment on is whether or not each packaged app stores it data in the hosts ~/.holochain directory, or inside the container? If its inside the container, then I guess you are saying that the image is a standalone, and versions... are taken care of inside the container?

Seems like a good honest early solution to me

**Comment by timotree3** [comment]
@christopherreay it seems like you have a lot of questions about designing the Docker situation. Because most of them aren't relevant to this PR, I request you bring them up in the docker slack channel.

**Comment by zippy** [comment]
Actually @timotree3 ,  I think it turns out that @christopherreay's question above is relevant to this PR, but I didn't get it till I tried actually using docker/run today (I guess I should have tired earlier!)   Here's the thing, the way the docker image used to work, it connected my host's .holochain directory to the docker image.   After this pull request that functionality is gone, which I didn't expect, and I didn't see anywhere in the threads above that you were removing that. This used to be documented in the main README (I wrote it) but I can't find it there any more, (possible that I also deleted it).  I think that's also part of why the UID thing is necessary and shouldn't be removed.

I will actually try to put it back, because I want to exercise my docker skills which so far I haven't.

**Pull request merged**
