### PR TITLE
get now returns JS object not JSON for JSON typed entries, closes #539

### LINKED ISSUE #539: Pre-parse JSON type entries when using `get` methods, so caller doesn't have to
```
var whole_entry = get(key);
var entry_content = JSON.parse(whole_entry.Entry);
```
would just become
```
var whole_entry = get(key);
var entry_content = whole_entry.Entry;
```
but `entry_content` would still become a JSON object

### PR DESCRIPTION
**Pull request by zippy**
This is a breaking change as all app uses of get that call JSON on the returned value will break!

### CODE REVIEW

**Comment by Connoropolous** [comment]
@zippy will this also parse strings to objects when using `getLinks` with config `Load: true`?

**Comment by zippy** [comment]
No it doesn't yet.  I think I may have had that as a separate ticket, but I guess I should just do that too in this ticket.  Thanks for reminding me.

**Comment by Connoropolous** [comment]
@zippy actually, I wrote a test in HoloWorld code to check my question, and it came back as being parsed already!

**Comment by philipbeadle** [comment]
Just let me update the builds on Clutter and HoloChat to use a new develop tagged Docker image then I'll merge this change.

**Comment by zippy** [comment]
hey @philipbeadle how are we doing on this?  can we merge soon?

**Pull request merged**
