### PR TITLE
First cut at Issue: 64 ExposedTo added to FunctionDef

### PR DESCRIPTION
**Pull request by GerryG**
Do we want to add any base functionality?

### CODE REVIEW

**Comment by GerryG** [comment]
How do you automagically link to issues #64 Is the issue this is for.

**Comment by zippy** [comment]
As per contribution guidelines... a test would be great that shows a function call failing and succeding based on the difference between the exposedTo value...

**Comment by GerryG** [comment]
Consider this a WIP until that is the case and we have agreed on the details. I'll withdraw and re-submit if we need to, but it is good to use the review comments to discuss and fix anyhow. Let me know you prefs for handling the work flows.

**Comment by GerryG** [comment]
I think the better work flow process for work in progress discussion is to add a PR local to my repo: https://github.com/GerryG/holochain/pull/2

I will close this one and open one that way as needed.

**Comment by GerryG** [comment]
Quick hint about how to configure the travis integration on my repo would be much appreciated.

**Comment by zippy** [comment]
I don't know how to do cross repo travis integration.  It looks to me like github handles that automatically when you do a pull request.

**Pull request closed without merging**
