### PR TITLE
Docker rework

### PR DESCRIPTION
**Pull request by timotree3**
A bunch of changes. I suggest looking at the individual commits to understand the difference better.

The image size halves so I think this is worth accepting unless I made some mistake.

### CODE REVIEW

**Comment by christopherreay** [comment]
So I and @timotree3 have had extensive converstations about this pull request. 

I suggest we remove the actual pull request, and work on creating a "production" dockerfile and a "development" dockerfile, and the relevant stuff to go around that.

To make this work absolutely properly there are some difficult questions.
1. how do we check for updates to the core code so that the core inside the docker containers is kept up to date for users?
2. can this be done automatically without breaking the relationship between the current core code and holochain apps themselves.
3. given 2., should it be the holochain apps that determine what version of the core they are running on? This is certainly possible, and may well be unavoidable in the "real world". 
4. Again I am reminded strongly of nvm. The Node community tech is, as far as I know, the most efficient and best community script management tech in existence today (not surprising, since javascript).

**Comment by timotree3** [comment]
I'm fine with closing this PR.


~Timo

**Comment by christopherreay** [comment]
ok. let's discuss and open some tickets about production and dev docker
stuff.

I reckon we pull the whole thing together now into an admin docker setup
that will eventually deal with dev, end user and windows scripting issues
in one place

**Comment by timotree3** [comment]
Closing this PR with the intention of integrating some of it's changes into future prototypes.

**Pull request closed without merging**
