### PR TITLE
110 interchain apikeys

### PR DESCRIPTION
**Pull request by zippy**
ok we now have bridging avialable in this branch.

Warning!!!  I wasn't able to write tests for the hdev and hcadmin use of all this, so it might be broken, so this pull request is also he testing help request!

You should be able to run tests or run the app with bridging enabled like this:

`hcdev -bridgeTo <path of dev directory of other app> test`

You do have to add one thing to the DNA of the app being bridged to and that is a list of the function that are available on the bridge, i.e.  `BridgeFuncs: {"someFunction","someOtherFunction"}`

### CODE REVIEW

**Comment by christopherreay** [comment]
So do we need to get the multinode testing done for this to be testable? Ive submitted a pull request for that also...

**Comment by zippy** [comment]
@christopherreay yah, I'll do your pull request today

**Comment by zippy** [comment]
this branch now also has the bidgeGenesis function implemented.

**Comment by zippy** [comment]
hey @tishakitkat this branch now has bridgeGenesis() implemented so you should no longer be blocked from going forward!

**Pull request merged**
