### PR TITLE
279 bin2hcdev 307 shifts in hcdev 309 go scenario

### PR DESCRIPTION
**Pull request by christopherreay**
So hc dev test scenario role is being run as required. 

There is no communciation between the hc instances

### CODE REVIEW

**Comment by zippy** [comment]
passing the env into the command isn't working.  Try this:  `HOLOCHAINCONFIG_LOGPREFIX=xxxx go test` and you will see both values in the ENV list from what's passed into testCommand:
```
    (string) (len=30) "HOLOCHAINCONFIG_LOGPREFIX=jane",
    (string) (len=30) "HOLOCHAINCONFIG_LOGPREFIX=xxxx",
```
and the log actually does use xxxx as a the prefix, but without using that it doesn' use 'jane'.  So, passing the env through to testCommand isn't working.

**Comment by christopherreay** [comment]
OK. Im guessing you got that information from the mutableContext output of the hcdev scenario tests?
 - [ ] Yes (lol)
So Ill write a comprehensive test for.. hcdev test and check it out

**Comment by zippy** [comment]
I merged into this branch my other hcdev tests and stuff and fixes I wrote for that, plus another small fix I figured out in that for more than one test to work we have to reset the values of debug/appInitialized/... in setupApp()

**Comment by christopherreay** [comment]
Doesnt each test block start with "app := setupApp()"?

**Comment by zippy** [comment]
yep but those variables are global, so each time the test run they have to get reset!

**Comment by christopherreay** [comment]
so they are package global?
And they should be reset in "setupApp"? That sounds very javascript to me. Surely they should be properties of the urfave app object?

**Comment by christopherreay** [comment]
is that possible?

**Comment by zippy** [comment]
yah, that would be better, but you can't add properties to objects after the fact like you can in Ruby, so this is the workaround...

**Comment by christopherreay** [comment]
so encapsulation or magic then :) OK. Fineadoodle do.

**Comment by zippy** [comment]
ok, the "Configured to connect to bootstrap server at: bootstrap.holochain.net:10000" in the test output is now gone, because that was being output at the point in time the service level configuration was being set, which is a separate value, and has it's own separate override.  In the latest commit I rationalized the message to make it more clear, and also only print it out if it's actually getting overridden by HC_DEFAULT_BOOTSTRAPSERVER, so you shouldn't even see it any more, because we are setting the value not via the default.  I like your using a flag, as that bypasses the whole ENV mess.

**Comment by lucksus** [comment]
superseded by #309

**Pull request closed without merging**
