### PR TITLE
fixes broken saving of new UUID and progentor on clone, #257

### PR DESCRIPTION
**Pull request by zippy**
Ok folks, I've fixed, I think, the but where UUID wasn't be regened after clone.  As part of your review I recommend checking out this branch, doing a make (so that you actually get new versions of hc and hcdev)  and running tests on the apps you've been developing to make sure that this didn't break anything.

### CODE REVIEW

**Comment by christopherreay** [comment]
So I ve run all the tests on this version of hcdev, which pass. I dont know if that means the bug is fixed! But its surely not broken the tests

**Comment by zippy** [comment]
Do you mean you ran tests in other apps using this version of HCdev?

**Comment by christopherreay** [comment]
yes thats exactly what I mean. I ran the tests on clutter using this version of hcdev

**Comment by christopherreay** [comment]
Im reading the output of "make" and it looks to me like it is running "go get ...holochain/cmd/hcdev" 

Does that mean that the "compiled" file or whatever is going to be the same as the source there? or that it is going to be compiled from master (since go get only ever deals in master)? ( @timotree3  )?

**Comment by christopherreay** [comment]
Nope. That works fine. I just tested it. make compiles the version on the current source tree. 

Why does the command "go get " come into it, since the documentation states clearly that go get downloads stuff from the repository?

**Comment by christopherreay** [comment]
```bash
christopher@holochain:~/go/src/github.com/metacurrency/holochain/cmd/hcdev$ grep "app.Version" hcdev.go 
        app.Version = fmt.Sprintf("0.0.1 (holochain %s)", holo.VersionStr)
christopher@holochain:~/go/src/github.com/metacurrency/holochain/cmd/hcdev$ make hcdev > /dev/null
make: *** No rule to make target 'hcdev'.  Stop.
christopher@holochain:~/go/src/github.com/metacurrency/holochain/cmd/hcdev$ cd ..
christopher@holochain:~/go/src/github.com/metacurrency/holochain/cmd$ cd ..
christopher@holochain:~/go/src/github.com/metacurrency/holochain$ make hcdev > /dev/null
christopher@holochain:~/go/src/github.com/metacurrency/holochain$ hcdev --version
hcdev version 0.0.1 (holochain 12)
christopher@holochain:~/go/src/github.com/metacurrency/holochain$ 
```

**Comment by timotree3** [comment]
Go get can also be used to install a local package. That is what it is
being used for here.


~Timo

On Jul 13, 2017 2:32 PM, "jayDayZee" <notifications@github.com> wrote:

Im reading the output of "make" and it looks to me like it is running "go
get ...holochain/cmd/hcdev"

Does that mean that the "compiled" file or whatever is going to be the same
as the source there? or that it is going to be compiled from master (since
go get only ever deals in master)? ( @timotree3
<https://github.com/timotree3> )?

**Pull request merged**
