### PR TITLE
#93 Add os.Exit in the  block after execution.

### PR DESCRIPTION
**Pull request by dukejones**

### CODE REVIEW

**Comment by timotree3** [comment]
I think @zippy wanted to use the urfave/cli for the exit code stuff.

**Comment by dukejones** [comment]
That will be cleaner, especially if/when we want differing exit codes for different error conditions.  This was an instant win for just non-zero on error.. Feel free to delete this when doing it properly..

**Comment by timotree3** [comment]
Sounds good. Thanks for the fix in the mean time. :)

**Comment by harlantwood** [comment]
👍👍👍

**Pull request merged**
